# Generated by Django 6.0.1 on 2026-01-19 19:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('days_per_year', models.DecimalField(decimal_places=2, default=0, help_text='Annual leave days entitlement', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('accrual_method', models.CharField(choices=[('annual', 'Annual Allocation'), ('monthly', 'Monthly Accrual'), ('none', 'No Accrual (Fixed)')], default='annual', max_length=20)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_documentation', models.BooleanField(default=False, help_text='Requires supporting documents (e.g., medical certificate)')),
                ('max_consecutive_days', models.IntegerField(blank=True, help_text='Maximum consecutive days allowed', null=True)),
                ('min_notice_days', models.IntegerField(default=0, help_text='Minimum days notice required before leave')),
                ('can_carry_forward', models.BooleanField(default=False, help_text='Can unused days be carried to next year')),
                ('max_carry_forward_days', models.DecimalField(decimal_places=2, default=0, help_text='Maximum days that can be carried forward', max_digits=5)),
                ('is_paid', models.BooleanField(default=True)),
                ('applies_to_probation', models.BooleanField(default=False, help_text='Available during probation period')),
                ('gender_specific', models.CharField(choices=[('all', 'All'), ('male', 'Male Only'), ('female', 'Female Only')], default='all', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=2, help_text='Number of working days', max_digits=5)),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_period', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('contact_during_leave', models.CharField(blank=True, max_length=100)),
                ('handover_notes', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='leave_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_hod', 'Pending HOD Approval'), ('pending_hr', 'Pending HR Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('hod_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hod_comments', models.TextField(blank=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('handover_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_requests', to=settings.AUTH_USER_MODEL)),
                ('hod_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_hod_approved', to=settings.AUTH_USER_MODEL)),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_hr_approved', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_rejected', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave.leavetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Repeats every year on same date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('entitled_days', models.DecimalField(decimal_places=2, default=0, help_text='Total days entitled for the year', max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=2, default=0, help_text='Days carried from previous year', max_digits=5)),
                ('accrued_days', models.DecimalField(decimal_places=2, default=0, help_text='Days accrued so far this year', max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, help_text='Days used this year', max_digits=5)),
                ('pending_days', models.DecimalField(decimal_places=2, default=0, help_text='Days in pending leave requests', max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave.leavetype')),
            ],
            options={
                'ordering': ['employee', 'leave_type', '-year'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
