# Generated by Django 6.0.1 on 2026-01-19 19:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_hr', 'Pending HR Approval'), ('pending_mgmt', 'Pending Management Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('mgmt_approved_at', models.DateTimeField(blank=True, null=True)),
                ('mgmt_comments', models.TextField(blank=True)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_nssf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_sha', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_housing_levy', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_hr_approved', to=settings.AUTH_USER_MODEL)),
                ('mgmt_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_mgmt_approved', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_prepared', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='BankFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('eft', 'EFT')], default='csv', max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('employee_count', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_files', to='payroll.payrollperiod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('band_1_limit', models.DecimalField(decimal_places=2, default=24000, help_text='Upper limit for 10% band', max_digits=12)),
                ('band_1_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5)),
                ('band_2_limit', models.DecimalField(decimal_places=2, default=32333, help_text='Upper limit for 25% band', max_digits=12)),
                ('band_2_rate', models.DecimalField(decimal_places=4, default=Decimal('0.25'), max_digits=5)),
                ('band_3_limit', models.DecimalField(decimal_places=2, default=500000, help_text='Upper limit for 30% band', max_digits=12)),
                ('band_3_rate', models.DecimalField(decimal_places=4, default=Decimal('0.30'), max_digits=5)),
                ('band_4_limit', models.DecimalField(decimal_places=2, default=800000, help_text='Upper limit for 32.5% band', max_digits=12)),
                ('band_4_rate', models.DecimalField(decimal_places=4, default=Decimal('0.325'), max_digits=5)),
                ('band_5_rate', models.DecimalField(decimal_places=4, default=Decimal('0.35'), help_text='Rate for income above band 4', max_digits=5)),
                ('personal_relief', models.DecimalField(decimal_places=2, default=2400, max_digits=12)),
                ('insurance_relief_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5)),
                ('insurance_relief_max', models.DecimalField(decimal_places=2, default=5000, max_digits=12)),
                ('disability_exemption', models.DecimalField(decimal_places=2, default=150000, max_digits=12)),
                ('nssf_tier1_limit', models.DecimalField(decimal_places=2, default=7000, max_digits=12)),
                ('nssf_tier1_rate', models.DecimalField(decimal_places=4, default=Decimal('0.06'), max_digits=5)),
                ('nssf_tier2_limit', models.DecimalField(decimal_places=2, default=36000, max_digits=12)),
                ('nssf_tier2_rate', models.DecimalField(decimal_places=4, default=Decimal('0.06'), max_digits=5)),
                ('sha_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0275'), max_digits=5)),
                ('housing_levy_rate', models.DecimalField(decimal_places=4, default=Decimal('0.015'), max_digits=5)),
                ('pension_max_deduction', models.DecimalField(decimal_places=2, default=20000, help_text='Maximum pension contribution deductible from taxable income', max_digits=12)),
                ('mortgage_interest_max', models.DecimalField(decimal_places=2, default=25000, help_text='Maximum mortgage interest deduction per month', max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('non_taxable_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('benefits_in_kind', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension_contribution', models.DecimalField(decimal_places=2, default=0, help_text='Defined contribution retirement scheme', max_digits=12)),
                ('owner_occupied_interest', models.DecimalField(decimal_places=2, default=0, help_text='Mortgage interest deduction (max 25,000/month)', max_digits=12)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_charged', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('personal_relief', models.DecimalField(decimal_places=2, default=2400, help_text='Monthly personal relief (KES 2,400)', max_digits=12)),
                ('insurance_relief', models.DecimalField(decimal_places=2, default=0, help_text='15% of insurance premiums, max KES 5,000/month', max_digits=12)),
                ('disability_exemption', models.DecimalField(decimal_places=2, default=0, help_text='Disability tax exemption (KES 150,000/month)', max_digits=12)),
                ('paye', models.DecimalField(decimal_places=2, default=0, help_text='Pay As You Earn tax after reliefs', max_digits=12)),
                ('nssf', models.DecimalField(decimal_places=2, default=0, help_text='NSSF contribution (Tier I + Tier II)', max_digits=12)),
                ('sha', models.DecimalField(decimal_places=2, default=0, help_text='Social Health Authority (2.75% of gross)', max_digits=12)),
                ('housing_levy', models.DecimalField(decimal_places=2, default=0, help_text='Affordable Housing Levy (1.5% of gross)', max_digits=12)),
                ('loan_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sacco_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowance_details', models.JSONField(blank=True, default=dict)),
                ('deduction_details', models.JSONField(blank=True, default=dict)),
                ('payslip_generated', models.BooleanField(default=False)),
                ('payslip_file', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name_plural': 'Payroll Entries',
                'ordering': ['employee__first_name', 'employee__last_name'],
                'unique_together': {('payroll_period', 'employee')},
            },
        ),
    ]
